### PR TITLE
fix: format date-time in current user locale

### LINKED ISSUE #154: Shows US time format, should adjust to users locale
Issue:
Current date format is always US format. 

Expected:
Users phone locale or TG locale should be used and not the servers locale which is in the US.

Image

### PR DESCRIPTION
**Pull request by kaf-lamed-beyt**
added a new hook, useUserLocale that returns a couple of functions to format date-time while considering the user's locale.

we first check for the telegram locale, if there isn't, fallback to the browser's locale.

closes #154

### CODE REVIEW

File: app/hooks/useUserLocale.ts [hunk 1]
```diff
@@ -0,0 +1,56 @@
+import { useEffect, useState } from 'react'
+import WebApp from '@twa-dev/sdk'
+
+export const useUserLocale = () => {
+  const [userLocale, setUserLocale] = useState<string>()
+
+  useEffect(() => {
+    try {
+      // @telegram-apps/sdk-react doesn't provide access to the language code property
```
Comment (BravoNatalie) [inline app/hooks/useUserLocale.ts:9]: You can access the `languageCode` directly from the user object, no need to install another library for that.
Reference: [telegram-apps docs](https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk/1-x/init-data/user#languagecode)
You can test this using the `user` provided in the Telegram provider.

When using `user.languageCode`, make sure to check if it includes the full locale, on my side, it only returns `'en'`, while my browser returns `'en-GB'`. So ideally, give preference to the browser's language setting and fall back to Telegram’s `languageCode` if needed.

**Review by BravoNatalie — CHANGES_REQUESTED** [review]

**Comment by kaf-lamed-beyt** [comment]
> Just keep in mind that the date and time format is working in some cases, for example, it’s showing correctly for me on prod

ah, i see. i thought the original issue referred to them being in U.S format all the time.

**Comment by BravoNatalie** [comment]
I'm getting the following error

**Comment by BravoNatalie** [comment]
I don't really know how to reproduce, but it happen with my two accounts on two different apps.

https://github.com/user-attachments/assets/e40fb65d-5b26-4f09-8b36-e4becddf389b

**Comment by kaf-lamed-beyt** [comment]
okay... i can see that you opened it with the menu. is that right, @BravoNatalie? 

i always open it by clicking the link BotFather generated for me, maybe that's why i couldn't reproduce it.

**Comment by kaf-lamed-beyt** [comment]
i still couldn't reproduce this error, @BravoNatalie, even after merging `main` into my branch
