### PR TITLE
fix: check for user plan before blocking upload

### LINKED ISSUE #244: No check for paid account on backup exceeded limit
None of my backups are working cause I have a paid account but the check for storage limit is always 5GB (and I'm over that)

### PR DESCRIPTION
**Pull request by BravoNatalie**
Fixes #244

### CODE REVIEW

File: app/lib/storacha.ts [hunk 1]
```diff
@@ -0,0 +1,138 @@
...
+  accountDID?: AccountDID
+) => {
+  if (!client) throw new Error('Storacha client is not initialized')
+  try {
+    const account = Object.values(client.accounts())[0]
+
+    let planResult
+    if (account) {
+      planResult = await account.plan.get()
+    } else if (accountDID) {
```
Comment (travis) [inline app/lib/storacha.ts:67]: question: why wouldn't the account exist here? is there somewhere in the app where we need to check this but we're not logged in? I'm a little confused how this would work if the account wasn't logged in, wondering if this whole branch is unnecessary. 

suggestion: if it is required please add a comment for clarity

**Review by travis — CHANGES_REQUESTED** [review]
a few questions and suggestions - most important are resolving the storachaAccount questions in the db accessor and the question about isPayingAccount

File: app/app/api/jobs/route.ts [hunk 2]
```diff
@@ -46,6 +46,7 @@ export async function GET() {
     const telegramId = getTelegramId(session.telegramAuth)
     const dbUser = await db.findOrCreateUser({
       storachaSpace: session.spaceDID,
+      storachaAccount: session.accountDID,
```
[the remark this answers is not in the document]
Comment (BravoNatalie) [reply app/app/api/jobs/route.ts:49]: The `findOrCreateUser` already uses it on the user creation, but I can update to also use in the query.

File: app/lib/storacha.ts (hunk 1 above)
Comment (BravoNatalie) [reply app/lib/storacha.ts:67]: This function is also used on the client side, in that case the user is logged in.

Comment (BravoNatalie) [reply app/lib/storacha.ts:71]: Yes, the `if (account)` block is for the client side, and the `else if (accountDID)` is for the server side. I’ve updated the delegations the client makes to the server, adding a new one for `plan/get`, that’s why we now have the proof. This part is being handled manually

Comment (travis) [reply app/lib/storacha.ts:71]: ahhhh, right - we're using the delegation rather than an actual account login, got it. ok this is fine - it would be a bit better if the underlying library supported "setting up" an account from a delegation, and I suspect it might not be that hard to do, but we can ship this for now and make that improvement later. thanks!

**Review by travis — APPROVED** [review]
